package main

func main() {
	execute()
}

//recover ile erroru catch ediyoruz. Erroru panic ile f覺rlatmak laz覺m.
func execute() {
	defer func() {
		if e := recover(); e != nil {
			println("hata yakaland覺:", e)
		}
	}()

	panic("exception f覺rlat")
}
